#
# SPDX-FileCopyrightText: Copyright © 2024 Idiap Research Institute <contact@idiap.ch>
#
# SPDX-FileContributor: Samy Tafasca <samy.tafasca@idiap.ch>
#
# SPDX-License-Identifier: CC-BY-NC-4.0
#

# ==================================================================================================================== #
#                                                EXPERIMENT CONFIGURATION                                              # 
# ==================================================================================================================== #


project:
    name: XGaze # name of the wandb project
    version: 1.0.0
    description: XGaze - Transformer encoder-decoder architecture for gaze target localization and recognition.
    root: /home/ubuntu/XGaze

# ------------------------------------------------------------------------------------------------------------------- #

experiment:
    name: run-name # name of the wandb job
    group: null # name of the wandb group
    task: train+test # combination of {train, val, test} separated by '+' sign
    dataset: gazefollow
    path: ${hydra:runtime.cwd} # to retrieve logs and checkpoints

# ------------------------------------------------------------------------------------------------------------------- #

data:
    num_people: 1 # int or -1 to include all people
    image_size: 512
    heatmap_size: 64
    heatmap_sigma: 3
    return_head_mask: False
    num_workers: 4
    gf:
        root: /home/ubuntu/XGaze/data/gazefollow/gazefollow_extended
        root_heads: null
        num_train_samples: 108955
# ------------------------------------------------------------------------------------------------------------------- #

model:
    XGaze:
        patch_size: 16
        token_dim: 768
        image_size: ${data.image_size}
        gaze_vec_dim: 2
        encoder_depth: 12
        encoder_num_heads: 12
        encoder_num_global_tokens: 1
        decoder_depth: 2
        decoder_num_heads: 8
        image_encoder_type: dinov3_hf # multimae, dinov3_hf
        hf_image_encoder_name: facebook/dinov3-vitb16-pretrain-lvd1689m
        hf_image_encoder_local_dir: /home/ubuntu/XGaze/weights/dinov3-vitb16
        hf_image_encoder_trust_remote_code: True
    pretraining:
        gaze_backbone: /home/ubuntu/XGaze/weights/gaze360_resnet18.pt
        image_encoder: /home/ubuntu/XGaze/weights/multimae-b_98_rgb+-depth-semseg_1600e_multivit-afff3f8c.pth
    weights: null # /!\ null (default), or path to a checkpoint (overrides pretraining weights)

# ------------------------------------------------------------------------------------------------------------------- #

loss:
    weight_heatmap: 100
    weight_angular: 3

# ------------------------------------------------------------------------------------------------------------------- #

optimizer:
    lr: 2e-4
    weight_decay: 3e-3

# ------------------------------------------------------------------------------------------------------------------- #

scheduler:
    type: cosine_warmup # cosine_warmup (default), null (no scheduler)
    warmup_epochs: 4

# ------------------------------------------------------------------------------------------------------------------- #

train: 
    seed: 10 # int or null for no seed
    matmul_precision: highest # highest (default), high, medium
    precision: 32 # 64 (double), 32 (full), 16 (16bit mixed), bf16-mixed (bfloat16 mixed). Defaults to 32.
    epochs: 20
    batch_size: 128
    accumulate_grad_batches: 1 # 1 (default, no accumulation)
    device: cuda
    resume: False 
    resume_from: null 
    checkpointing:
        monitor: "metric/val/dist" # "metric/val/dist" (default), "loss/val", etc.
        mode: "min" # "min" (default), "max"
    freeze:
        gaze_encoder: False 
        image_tokenizer: False
        image_encoder: True
        gaze_decoder: False
    swa:
        use: True
        lr: 1e-5
        epoch_start: 17
        annealing_epochs: 3

# ------------------------------------------------------------------------------------------------------------------- #

val: 
    checkpoint: null
    batch_size: 128
    device: ${train.device}

# ------------------------------------------------------------------------------------------------------------------- #

test:
    checkpoint: null # or experiments/yyyy-mm-dd/hh-mm-ss/checkpoints/last.ckpt to test from an existing experiment
    batch_size: 128
    device: ${train.device}

# ------------------------------------------------------------------------------------------------------------------- #

wandb:
    log: True
    entity: null # /!\ null, or your wandb entity
    watch: null # /!\ null, gradients, parameters, all
    watch_freq: 500

# ------------------------------------------------------------------------------------------------------------------- #

hydra: 
    run: 
        dir: ./
    sweep:
        dir: ${hydra.run.dir}
        subdir: ${hydra.job.num}
    job: 
        chdir: False
